### ISSUE TITLE
Icon looks a bit too much like a + (for adding elements) rather than a sight

### ISSUE THREAD

**Issue by mystor** [uniphil/dom-destroyer#2]
Possibly consider using an `x` instead of a `+` in the middle?

**Comment by jessegilbride** [comment]
Agreed, an "x" would be less confusing than a "+".  If you were to alter the current icon, I'd recommend making it look more like crosshairs (as in a riffle sight).

**Comment by uniphil** [comment]
i'm sure y'all have been waiting eagerly for... `*checks watch*` hmm what nearly 7 years? 😭

<img width="29" alt="Screen Shot 2020-12-13 at 01 17 35" src="https://user-images.githubusercontent.com/205128/102004709-1efae780-3ce1-11eb-8dd0-1cd0a538117b.png">
