### ISSUE TITLE
Extension keeps working after hitting the escape key

### ISSUE THREAD

**Issue by jessegilbride** [uniphil/dom-destroyer#3]
I expected the behavior of the extension to be such that after hitting the escape key the extension toggles to an off state, but that's not happening.

Steps to reproduce:
1) load a webpage and then clicking the "DOM Destroyer" button
2) hovering the mouse over an element causes the element to be highlighted in red (as expected)
3) clicking on the highlighted element causes it to be removed (as expected)
4) press escape key and highlighting over elements with mouse hover no longer occurs, seeming to indicate the extension is not activated
5) clicking on any element in the webpage removes that element (as unexpected)

You might get a hint as to the proper implementation if you're able to look at how the "Click to remove element" extension works (linked below).

https://chrome.google.com/webstore/detail/jcgpghgjhhahcefnfpbncdmhhddedhnk

**Comment by uniphil** [comment]
fixed! submitted to FF & Chrome, pending review.
